baseURL: 'https://aliif.space/'
languageCode: en-us
title: Aliif Arief Homepage
googleAnalytics: ""
disqusShortname: "aliif"
enableEmoji: true
//preserveTaxonomyNames: true
footnotereturnlinkcontents: â†©
disableHugoGeneratorInject: true
pluralizeListTitles: false
pygmentsCodeFences: true
pygmentsUseClasses: false
pygmentsStyle: "dracula"
minify: true
enableGitInfo: true
metaDataFormat: yaml

permalinks:
  writing: /:slug/
  projects: /:slug/
  pages: /:slug/

author:
  name: Aliif Arief
  email: me@aliif.space
  twitter: 'lifrief'

taxonomies:
  tag: tags

menu:
  main:
    - name: "Home"
      url: "/"
      weight: 1
    - name: "About"
      url: "/about/"
      weight: 2
    - name: "Writing"
      url: "/writing/"
      weight: 3
    - identifier: projects
      name: Projects
      url: /projects/
      weight: 4

params:
  description: "I am a first year software engineering student at Gadjah Mada University with a focus on backend application development."
  images: 
  - https://og.tailgraph.com/og?fontFamily=Inter&title=Aliif%20Arief's%20Homepage&titleTailwind=text-gray-800%20font-bold%20text-6xl&text=I%20am%20a%20first%20year%20software%20engineering%20student%20at%20Gadjah%20Mada%20University%20with%20a%20focus%20on%20backend%20application%20development.&textTailwind=text-gray-700%20text-2xl%20mt-4&logoTailwind=h-8&bgTailwind=bg-white&footer=aliif.space&footerTailwind=text-blueGray-500&t=1652777858725&refresh=1
  FooterText: "Aliif Arief"

frontmatter:
  author: 'Aliif Arief'
  github: 'https://github.com/aliifam'
  twitter: 'lifrief'
  lastmod:
  - lastmod

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    anchorLineNos: false
    codeFences: true
    guessSyntax: false
    hl_Lines: ""
    lineAnchors: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    noHl: false
    style: "dracula"
    tabWidth: 4

sitemap:
  changefreq: monthly
  filename: sitemap.xml
  priority: 0.5

outputFormats:
  RSS:
    mediatype: application/rss
    baseName: atom


